---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by siyin.liu.
--- DateTime: 2021/4/11 21:58
---
--[[
match()方法：
    字符串中，第一个配对成功的，返回所有结果，没有则返回nil
]]
print("===查找字符串”Hello,EveryOne!“字符串中字母======")
print(string.match("Hello,EveryOne!","%a")) --output H

print("===查找字符串”Hello,EveryOne!“字符串中非字母======")
print(string.match("Hello,EveryOne!","%A")) --output ,
