---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2021/4/12 11:28
---
--[[
gsub()函数类似sub()函数也用于模糊匹配。区别是迭代器可以返回多个匹配结果。
    示例：在指定字符串中，查找与替换所有”敏感“字段。
]]
print("===对指定输入字符串自动替换敏感字段。（国家领导人，恐怖信息，黄色信息）=====")
str1 = "刘加萨洛克jfk到了打架和美女和美女不要杀人啊啊" --输入源字符串
strKeyWord = {"刘","杀人","美女"}    --敏感字库
for i = 1, #strKeyWord do
    str1 = string.gsub(str1,strKeyWord[i],"*")
end
print(str1)

