---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2021/4/12 14:59
---
--[[
综合小案例：
    1>对登录名称(昵称、密码等）进行合法性检查
    2>将数字转换为汉字行数字
]]
print("开发综合小案例：游戏中的登录账号，要必须以”字母、数字、下划线“组成，且数字不能开头。")
strAccount = "a_bc6688cd"            --要检查的指定账号
numCheckPos = nil                   --查询账号信息位置
pattern1 = "[^%w_]"                 --查找模式匹配字符串
numCheckPos = string.find(strAccount,pattern1) --查询出非字母、数字、下滑线的内容
if numCheckPos == nil then
    --表示查询不到非法的信息
    local strFirstLetter = string.sub(strAccount,1,1)
    print("strFirstLetter:"..strFirstLetter)
    if (string.match(strFirstLetter,"%D") == nil) then
        print("输入的账号，不能以数字开头，请重新输入")
    else
        print("输入账号信息合法，进入下一页!")
    end
else
    print("输入的账号包含非法信息，请重新输入【只能”字母、数字、下划线“组成】")
end
