---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by siyin.liu.
--- DateTime: 2021/4/20 22:06
---
--[[
协同的挂起：
    通过调用coroutine.yield使协程暂时让出执行权。此协程让出执行权后，对应的最近coroutine.resume
    函数会立刻返回。
]]

--协同的挂起演示
cor1 = coroutine.create(
        function()
            for i = 1,10 do
                print(i)
                if i == 3 then
                    print(coroutine.status(cor1))               --当前协同的状态
                    print(coroutine.running())                  --当前协同是否在运行中
                end
                coroutine.yield()
            end
                                            --协同的挂起
        end
)
coroutine.resume(cor1)
coroutine.resume(cor1)
coroutine.resume(cor1)
coroutine.resume(cor1)
print(coroutine.status(cor1))               --当前协同的状态
print(coroutine.running())                  --当前协同是否在运行中