---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by siyin.liu.
--- DateTime: 2021/4/20 22:21
---
--[[
    带参协同：使得协程的功能与灵活性进一步提高。
    步骤：
        1 > 定义带有形参的函数，且定义为协同程序。
        2 > 使用coroutine.resume(协同，“协同参数”）方式传入协同的实参。
]]
cor1 = coroutine.create(
        function()

        end
)
