---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2021/4/21 18:46
---
--[[
演示带参协同之间状态管理：
    下面示例中”A协同“中启动”B协同“。然后在”B协同“中，查看”A协同“的状态。
    这个示例充分表名Lua一项非常重要的特性：”多个协同程序在任意时刻只能运行一个协同程序“。
    进一步总结：Lua提供一种”非对称协同程序“，也就是Lua提供了两个函数来控制协同程序的执行，一个用于挂起执行，另一个用于恢复执行。
]]
local cor_B = coroutine.create(
        function(corAPara)
                print("协同B中，检查输入参数协同A的状态",coroutine.status(corAPara))
        end
)
local cor_A = coroutine.create(
        function(corAPara)
            print("协同A中，检查输入参数协同A的状态",coroutine.status(corAPara))
            --coroutine.yield()
            coroutine.resume(cor_B,corA)
        end
)
--测试
--开始两个协同的状态
print("协同A状态:",coroutine.status(cor_A))
print("协同B状态:",coroutine.status(cor_B))
--启动协程A
coroutine.resume(cor_A,cor_A)
--coroutine.resume(cor_B,cor_A)
