---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by siyin.liu.
--- DateTime: 2021/4/21 21:28
---
--[[
演示yield返回值技术：
    前面我们所演示的所有协同，在挂起协同的时候，yield都是没有参数的。
    当挂起正在调用的协同的执行，传递给yield的参数会转为resume的额外返回值。即这里的yield参数，可以作为
    启动本协同的返回值使用。
]]
--演示yield参数，可以作为返回数值（返回到resume()调用协同的地方）
cor1 = coroutine.create(
        function()
                coroutine.yield("Hello",68)
        end
)
--测试，启动协同
--print(coroutine.resume(cor1))   --output:   true(表示协同是否正确被调用)    Hello   68
resultReturn,value1,value2 = coroutine.resume(cor1)
print("返回的数值1",value1)
print("返回的数值1",value2)

