---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by siyin.liu.
--- DateTime: 2021/4/26 21:36
---
--[[
文本文件读取所有行数据

]]
file = io.open("test1.txt","r");
--输出显示读取多行信息
for line in file:lines() do
    print(line)
end
io.close(file)

