---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by siyin.liu.
--- DateTime: 2021/5/3 16:56
---
--[[
典型案例：覆盖写入文本文件
]]
file = io.open("test2.txt","w")
io.output(file)
io.write("This is Lua Data.大家好\r\nThis is Second Lines")
io.close()
