---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by siyin.liu.
--- DateTime: 2021/5/3 17:10
---
--[[

]]
file = io.open("test2.txt","a")
io.output(file)
io.write("\r\n 这是增加的最后一行末尾信息")
io.close(file)
