---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by siyin.liu.
--- DateTime: 2021/4/11 18:28
---
--[[
    字符串与ASCII码之间的转换
        字符转ASCII码 string.byte
        ASCII码转字符 string.char
    字符串的拷贝
        string.rep 字符串的拷贝
]]
print("===字符转ASCII码====")
print(string.byte("a")) --字母a 转换成ASCII码 output 97
print(string.byte("A")) --字母A 转换成ASCII码 output 65
print(string.byte("AbcHello",2)) --指定字符串中某个位置进行转码，默认为第一个位置
print(string.byte("AbcHello",2,5))--指定从字符串某个位置开始，到某个位置结束，进行转码。

print("=====ASCII码转字符=======")
print(string.char(97)) --output a
print(string.char(97,65)) --output aA
print(string.char(65,78,99)) --output ANc

print("=========字符串的多个拷贝==================")
print(string.rep("Hello",3)) --第一个参数：要拷贝的字符串 第二个参数：拷贝次数
