---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2021/4/12 10:52
---
--[[
gmatch()函数类似match()函数也用于模糊匹配。区别是自带迭代器可以返回多个匹配结果：
]]
print("======gmatch:在指定字符传中查找英文单词=====")
s1 = "Hello world every one"
pattern1 = "%a+"
for word in string.gmatch(s1,pattern1) do
    print(word)
end
print("======gmatch:在指定字符传中查找英文单词示例2=====")
s2 = "hello#World*Every@One"
pattern2 = "%a+"
for word in string.gmatch(s2,pattern2) do
    print(word)
end
print("===gmatch:输出字符串”Mobil:13166668888, My Phone: 01066668888“中所有电话号码信息===")
s3 = "Mobil:13166668888, My Phone: 01066668888"
pattern3 = "%d+"
for number in string.gmatch(s3,pattern3) do
    print(number)
end
print("====输出字符串”luaC#Java_PasicalC++C“中所有以”C“开头的编程语言====")
s4 = "luaC#Java_PasicalC++C"
pattern4 = "C%p*"
for l in string.gmatch(s4,pattern4) do
    print(l)
end