---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2021/3/8 11:13
---
--[[
标准函数库
    Lua的标准函数库也是lua的内置函数，主要分为以下三类：
        数学函数
        字符串函数
        操作系统库
            应用案例：使用操作系统的时间系统函数，配合随机函数，开发准确的随机数函数。

]]
