---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2021/3/8 17:58
--[[
自定义开发随机函数
---]]
--得到一个真实的随机数
function GetTrueRandom(min, max)
    local strTime = tostring(os.time())
    print("strTime",strTime) --调试使用
    --得到一个反转字符串
    local strRev = string.reverse(strTime)
    local strRandomTime = string.sub(strRev,1,6)
    print("strRandomTime",strRandomTime) --调式
    --设置时间种子
    math.randomseed(strRandomTime)
    --输出随机数
    return math.random(min,max)
end
numResult = GetTrueRandom(1,100)
print("最终随机数:", numResult)