---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2021/3/11 19:47
---
--[[
函数的本质
    Lua函数本质是匿名的，即没有名称。讨论一个函数，本质是讨论一个持有此函数的变量。
    函数与普通类型的数值权力相同。
    A:函数可以存储在变量或者table中，也可以作为实参传递给其他函数，还可以作为其他函数的返回值。
    B：本质上函数就是一条语句，可以将其存储在全局变量中，也可以存储在局部变量中
]]
--函数本质是匿名的
function GetNum1(num) --定义函数1
    return num * 2
end
GetNum2 = function(num) --定义函数2：把一个函数指定一个变量
    return num * 2
end

--调用
print(GetNum1(9))
print(GetNum2(10))
-- 函数可以存储在表中
funArray  = {}
funArray[1] = GetNum1;
funArray[2] = GetNum2;
for i = 1, #funArray do
    print(funArray[i](10 * i))
end