---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2021/1/13 11:59
---
--[[
lua变量类型(数据类型）
    nil表示空数据，等同C#的null
    boolean 布尔类型
    string 字符串类型。可以使用双引号也可以用单引号
    number小数类型。注意：lua中没有整数类型
    table类型。表示一个集合。下表序号是从1开始的。（lua没有class概念，lua的面向对象就是用”表“实现）
    function 表示由lua（或者C）编写的函数。（类似C#的方法）
    userdata 表示任意存储在变量中的C数据类型。
    thread 表示执行的独立线程（本质是”伪多线程“，是协程的概念），用于执行协同程序。
]]
print("lua语言的数据类型")
print("字符串 数据类型: "..type("你好"))
print("number 数据类型:"..type(884))
print("boolean 数据类型:"..type(true))
print("nil 数据类型:"..type(nil))
print("table 数据类型:"..type({1,2,3}))

function fun1()
    return 10
end
print("函数 函数数据类型："..type(fun1))