---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2021/1/18 16:06
---
--[[
函数赋值
    定义变量，把函数直接赋值给它，从而获得相同功能。
]]
function FuncName(num1,num2)
    return num1 + num2
end
-- 函数赋值
fun2 = FuncName

-- 获取函数的返回值
resultFun2 = fun2(10,100)
print("一个新的变量得到函数的引用 resultFun2:"..resultFun2)
-- 注意：函数中由于我们的函数参数没有类型，所以在没有(编译）运行前，计算机是无法发现错误，这在C#/Java等编译型语言中，是一个明显弱点
-- resultFun2_1 = fun2("同学们","大家好")-- 报错 attempt to perform arithmetic on local 'num1' (a string value)
