---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2021/1/18 17:43
---
--[[
匿名函数
    匿名函数定义：没有函数名称的函数。
    匿名函数如何调用？
        一个没有名称的函数，只有通过赋值给一个变量(相当于C#的委托注册方法），我们通过调用这个（函数）变量来间接调用这个匿名函数。
]]
--学习匿名函数
hideFunc = function (num1,num2)
    print("我是一个匿名函数 sum="..(num1 + num2))
end
--调用匿名函数(本质调用的是匿名函数赋值给的变量)
hideFunc(66,88)

function AddNum(num1,num2,printFunc)
    local result = num1 + num2
    printFunc(result)
end

AddNum(10,20,function(result)
    print("result="..result)
end)