---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2021/4/19 15:25
---
--[[
回顾OOP封装类,本质是用一个Table来模拟一个类.
按照Table的本质,Table是Lua中主要的数据结构机制,可以作为其他数据结构的基础.
]]
Person = {}
--定义字段
Person.Name = "唐三"
Person.Gender = "男"
--定义方法
function Person:PersonInfo()
    print(string.format("人员信息  姓名: %s 性别:%s",self.Name,self.Gender))
end
--调用方法
print("名称:",Person.Name)
Person:PersonInfo()