---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2021/4/19 16:08
---
--[[
进一步优化Lua的继承机制
]]
Person = {}
--定义字段
Person.Name = "唐三"
--定义方法
Person.Gender = "男"

Person.Address = "北京"
function Person:PersonInfo()
    print(string.format("人员信息  姓名: %s 性别:%s",self.Name,self.Gender))
end

--定义一个实现继承机制的特殊方法
function Person:New(name, gender)
    local subClass = {}
    self.__index = self
    setmetatable(subClass,self)
    subClass.Name = name
    subClass.Gender = gender
    return subClass
end

--定义子类
local Student = Person:New("朱竹青","女")
Student:PersonInfo()
function Student:PersonInfo()           --测试方法覆盖
    print("重写 ")
end
print(Student.Name)
print(Student.Gender)
Student:PersonInfo()

