---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2021/3/12 10:22
---
--[[
闭包：
    一个函数中嵌套子函数，子函数可以使用父函数中的局部变量，这种行为就是”闭包“
    可以简略归纳为：闭包=函数 + 引用环境
    闭包的特点：
        闭包中的内嵌函数可以访问外部函数已经创建的所有局部变量，这些变量称为内嵌函数的”upvalue“
    闭包与一般函数的区别：
        闭包只是在形式表现上像函数，但实际上不是函数。函数只有一个实例，定义后逻辑就确定了，不会执行时发生变化。

]]
--无参数闭包 内部嵌入内部函数
function Func()
    local i = 0
    print("--   A --i",i)
    return function() --内部嵌入的匿名函数，i 变量，称为内嵌函数的”upValue“.这里的i变量即不是全局变量，也不是局部变量。这里应该称为”非局部变量“
        print("--   B --i",i)
        i = i + 1
        print("--   C --i",i)
        return i;
    end
end
f1 = Func()
print(f1()) -- 输出结果 1
print(f1()) -- 输出结果 2
print(f1()) -- 输出结果 3
print(f1()) -- 输出结果 4

--
