---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2021/3/16 17:10
---
--[[

]]
--自定义“迭代器”
function Itrs(tableArray)
    local i = 0
    return function()
        i = i + 1
        return tableArray[i]
    end
end
--定义一个表
myTable = {1,32,12,34,54,26,12}

iterator =Itrs(myTable)
--迭代输出方式1
while(true) do
    local j = iterator();
    if(j == nil) then
        break
    end
    print("(while) j=",j)
end
--迭代输出方式2
for m in Itrs(myTable) do --利用了for.. in 遇到nil停止循环的特性
    print("for m:",m)
end
