---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2021/4/1 18:16
---
--[[
    函数unpack
        接受一个数组作为一个参数，并从下标1开始返回该数组的所有元素。
    注意事项：
        1：unpack 可以很容易的把table集合中数据“解包”输出。
        2、与之对应的是table.concat()函数，可以把table集合中数据“压缩”为一个字符串输出。

]]
