---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DavidLiu.
--- DateTime: 2021/1/11 18:18
---
--[[
    常用的快捷方式介绍
     Alt+Shift+F10,运行程序。（需要先选择运行的lua脚本）
    直接运行程序
     Ctrl+F5，Ctrl+Shift+F10,直接快速运行当前lua脚本。
    注释
    Ctrl+/  这个是多行代码分行注释，每行一个注释符号。
    Ctrl+Shift+/ 这个是多行代码注释在一个块里
]]
print("women")
print("今天遇到个傻子")
