---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2021/1/12 14:52
---
--[[
字符串基础：
    字符串，可以使用双引号与单引号。
    可以用两个方括号，来表示‘一块’字符串。（即：多行字符串）
    字符串进行链接的时候，Lua使用“..”两个点做链接。（C#的“+”可以链接字符串，本质是做了操作符重载，lua没有）
    如果字符串应用“+”号，则字符串会自动转换为number类型处理（但必须保证是“数字字符串”，否则报错）
    字符串与数值类型，使用..链接，一般没有问题，不会报错。但数值类型如果可能为nil，则推荐加入tostring函数
    使用#符号，除了可以取得字符串得长度，还可以取得表得长度。
    可以使用tostring()把数值型转为字符串。
    可以使用tonumber()把字符串转为数值型
]]

str1 = '单引号字符串'
str2 = "双引号字符串"
--定义多行字符串
strMultiLine =[[
    <html>
        <head></head>
        <body>
            <a href="http://www.baidu.com">百度</a>
        </body>
    </html>
]]
print(str1)
print(str2)
print("以下输出多行字符串")
print(strMultiLine)
--字符串链接
str = "123"
print("输出变量 str=".. str) -- ".."表示字符串链接
--字符串转换（自动转换1）
print("2.2" + "30") -- 在lua中会输出2.2和30的和，在C#中会输出 “2.230”
--字符串转换（自动转换2）
print("2.2" + 10) -- 输出结果12.2
--求字符串长度
print(#str) -- 输出结果：3
str4 = "同学们好好"
print(#str4) -- 输出结果为12这跟编码格式有关
--字符串中有两个重要的转换函数（字符串与其他类型的转换）
--tonumber()、tostring()
--tonumber隐式转换
strNum1 = "888"
num2 = 666
res1 = strNum1 - num2;
print("res1:",res1);
--tonumber显示转换
res2 = tonumber(strNum1) - num2
print("做显示转换 res2:".. res2)

--tostring隐式转换
strName = "同学们"
res3 = strName..num2
print("隐式转换res3:", res3)
--tostring显示转换
res4 = strName.. tostring(num2)
print("显示转换res4:", res4)
------------------------------------------------
--关于字符串与数值类型是否可以直接加减？

str1 = "同学们"
num1 = 666
--res1 = str1 + num1 --字符串如果含有非数字是不能与数值类型进行相“加”

--必须用tostring()的场合一
numArray1 = {12,15,80}
--print("表的内容: "..numArray1) --报错,表不能自动转换为字符串所以链接操作会报错。
print("表的内容:"..tostring(numArray1)) --输出：00C29618
--必须用tostring()的场合二
num = nil -- num变量为空(相当于c#的null)
--print("num="..num) --报错 nil类型的变量无法自动转换为字符串
print("num="..tostring(num))
