---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2021/1/13 15:46
---
--[[
全局与局部变量
    lua变量默认都是全局性的，定义局部变量则需要关键字local来修饰。
    lua语句块(if、for等）与函数中，定义的默认也都是全局变量。
    lua中也可以直接使用do ... end来定一个语句块。
        eg:
            do
                local a = 10
                local b = 20
            end
    如果你要删除一个全局变量，只需要给变量赋值nil
        eg:b = 10 print(b) b = nil
]]
