---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yangf.
--- DateTime: 2021/1/17 22:12
---
--[[
流程控制语句
if判断语句
    单分支语句：
    if () then --逻辑表达式小括号可写可不写

    end
    双分支语句：
    if() then --逻辑表达式小括号可写可不写
        [body]
    else
        [body]
    end
    多分支语句：
    if() then --逻辑表达式小括号可写可不写
        [body]
    elseif () then --逻辑表达式小括号可写可不写
        [body]
    ....
    else
        [body]
    end
if后配合写then语句
多分支语句的elseif关键字必须连着没有空格，且跟then关键字。
if后面逻辑表达式，括号可以不加
]]
if (true) then
    print("这是但分支语句"); --注意表达式分号结尾可以不写
end
num1 = 10
num2 = 10
if num1 > num2 then
    print("num1 > num2双分支语句")
else
    print("num2 < num3双分支语句")
end

num3 = 11;
if num1 > num2 then
    print("num1 > num2 多分支语句")
elseif (num2 > num3) then
    print("num2 > num3 多分枝语句")
else
    print("其他 多分枝语句")
end