---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2021/1/18 13:39
---
--[[
    While循环
        while结构(先判断，后实现）
        while(...) do  -- ()可以不要
            todo....
        end
    repeat 关键字(先实现，后判断）相当于C#中的do..while
        repeat
            todo...
        until(...) --()可以不要
    for循环分为数值循环，泛型循环(类似C#中的foreach)
            for 数值循环语句结构：
            for 变量名称=初始值，结束值，（步长）do
                [循环体]
            do
            for 泛型循环语句结构
                ipairs 与 pairs迭代器
                    ipairs 遍历顺序的集合。（中间序号不能中断，遇到nil数值就停止)。一般用于数组类型集合的遍历。
                    pairs遍历集合中所有数据。（序号可以中断），一般用于键值对类型集合的遍历。
                for 变量列表 in 迭代函数 do
                    [循环体]
                end


]]
num1 = 1;
num2 = 5
while(num1 < num2) do
  num1 = num1 + 1 -- C#语言中有i++/++i,lua没有
  print("num1="..num1)
end
i=1
sum = 0
while i < 100 do
    if(i % 2 == 0) then
        sum = sum + i
    end
    i = i+1
end
print("输出1-100所有偶数累加和="..sum)

--repeat 先实现后判断
print("repeat 测试")
j = 1
repeat
    print(j)
    j = j + 1
until (j > 2)
print("for 测试")
for i = 1, 2 , 1 do
    print("for正循环i="..i)
end
for i = 10, 1, -2 do
    print("for倒循环i="..i)
end
for j = 0, 10 ,3 do
    print("j="..j)
end
-- 泛型循环
myArray = {0,3,5,10} -- 定义表(相当于C#中的数组与集合类)
for k,v in ipairs(myArray) do --这里的k相当于索引，索引从1开始
    print("k="..k..",v="..v)
end
myArray2 = {num1 = "张三",num2 = "李四",num3 = "王五"} --定义表(具备键值对)
for k,v in pairs(myArray2) do --这里的k相当于键
    print("myArray2 k=",k,"v=",v)
end