---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by siyin.liu.
--- DateTime: 2021/4/13 20:08
---
--[[
使用Table定义 二维数组(矩阵)
]]
print("=====定义简单的二维数组=====")
local doubleArray = {}
local array_Row_1 = {} --第一行
local array_Row_2 = {} --第二行
array_Row_1[1] = 10
array_Row_1[2] = 20
array_Row_2[1] = 100
array_Row_2[2] = 200
doubleArray[1] = array_Row_1
doubleArray[2] = array_Row_2

