---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2021/4/14 9:10
---
--[[
链表：
    由于Lua中Table是动态的实体，所以在Lua实现链表是非常方便的。
    每一个链表结点以Table来表示，结点包含两个值Next和Value,注意尾结点的Next应该是nil
]]
local linkList = {}
