---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2021/5/17 11:09
---
C007_model = {}
C007_model.height = 170
C007_model.width = 100
function C007_model:AddAge()
    self.age = 100
end
function C007_model:SetHeight(height)
    self.height = height;
    print("height", self.height)
end

function C007_model:SetWidth(width)
    self.width = width
    print("width",self.width)
end
function C007_model:ToString()
    if self.age then
        print("height:"..self.height..",width:"..self.width..",age:"..self.age)
    else
        print("height:"..self.height..",width:"..self.width)
    end

end
return C007_model