---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2021/5/17 11:09
---
local C007_model = {}
C007_model.height = 170
C007_model.width = 100

C007_model.SetHeight = function(height)
    C007_model.height = height;
    print("height", C007_model.height)
end

C007_model.SetWidth = function(width)
    C007_model.width = width
    print("width",C007_model.width)
end
function C007_model.ToString()
    print("height:"..C007_model.height..",width:"..C007_model.width)
end
return C007_model