---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2021/8/31 15:58
---
C008_table = {}
--C008_table.height = 170
--C008_table.width = 100

function C008_table:SetHeight(height)
    self.height = height;
end

function C008_table:SetWidth(width)
    self.width = width
end
function C008_table:ToString()
    print("height:"..self.height..",width:"..self.width)
end
