---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2021/4/16 10:02
---
--定义Table
tab_1 = {10,20,50}
tab_2 = {35,70,80}
tab_3 = {num1 = 2,num2 = 3,num3 = 8}
tab_4 = {num1 = 10, num2 = 40, num3 = 50}
--测试两个表相加
--tabRes = tab_1 + tab_2                    --两个表直接做算数运算，会导致报错
--第二步：定义“元表”（核心计算）
setTable = {}                               --定义一个”元表“
function setTable.Adding(tab1,tab2)
    local addTableRes = {}                  --返回结果
    for i,v in pairs(tab1) do
        if(v == nil) then
            break
        end
        addTableRes[i] = tab1[i] + tab2[i]
    end
    return addTableRes
end
function setTable.Sub(tab1,tab2)
    local subTableRes = {}
    for i, v in pairs(tab1) do
        if(v == nil) then
            break
        end
        subTableRes[i] = tab1[i] - tab2[i]
    end
    return subTableRes
end
--第三步：设置元方法
setTable.__add = setTable.Adding            --Adding函数作为”__add“的实际执行的元方法
setTable.__sub = setTable.Sub
--第四步：设置元表
setmetatable(tab_1,setTable)
setmetatable(tab_2,setTable)
setmetatable(tab_3,setTable)
setmetatable(tab_4,setTable)
--第五步：测试输出
print("测试表的加法")
tabResult = tab_1 + tab_2
for i = 1, #tabResult do
    print(tabResult[i])
end
print("测试表的减法")
tabResult = tab_1 - tab_2
for i = 1, #tabResult do
    print(tabResult[i])
end
print("测试表的加法")
tabResult2 = tab_3 + tab_4
for i,v in pairs(tabResult2) do
    print(i,v)
end
print("测试表的减法")
tabResult2 = tab_3 - tab_4
for i,v in pairs(tabResult2) do
    print(i,v)
end