---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by siyin.liu.
--- DateTime: 2021/4/18 16:37
---
--[[

]]
--1、定义Table
    tab1 = {10,20,30,40,110,500}
    tab2 = {str1 = "haha",str2 = "CSharp",str3 = "Lua", str4="C++"}

    print(tab1) --没有定义元方法打印的是地址
    print(tab2) --没有定义元方法打印的是地址
--2、定义元表
    metatable1 = {}
    function metatable1.ToString(tab)
        local tableResult = {}
        for k,v in pairs(tab) do
            tableResult[#tableResult + 1] = v
        end
        return table.concat(tableResult,",")
    end
--3、设置元方法
    metatable1.__tostring = metatable1.ToString
--规定元方法不允许被修改
    metatable1.__metatable = "不能修改受保护的元表(Don't modify protected metatable)"
--4、设置原表
    setmetatable(tab1,metatable1)
    setmetatable(tab2,metatable1)
--5、测试输出
    print("tab1=",tab1)
    print("tab2=",tab2)
--获取元表
    print(getmetatable(tab1)) --不设置__setmetatable输出的是metatable1的地址
                                --设置了后输出的是__setmetatable被赋值的内容

--测试再次设置原表
--print("测试再次设置元表")
    --setmetatable(tab1,{})
    --print(tab1)