---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by siyin.liu.
--- DateTime: 2021/4/18 17:23
---
--[[

]]
--1、定义原表
tab1 = {str1 = "子弹",str2 = "不过", str3 = "大傻逼"}
print(tab1.str1)
print(tab1.str4)
--2、定义元表
setTable = {}
function setTable.TipNotFinding()
    return "您查询的表中没有对应的记录"
end
--3、设置元方法
setTable.__index = setTable.TipNotFinding
--4、设置原始表对应的元表
setmetatable(tab1,setTable)
--测试
print(tab1.str4)
print(tab1["str1"])
print(tab1["str4"])