---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by siyin.liu.
--- DateTime: 2021/4/18 18:05
---
tab1 = {str1 = "科长",str2 = "处长"}
print(tab1.str1)
print(tab1["str2"])
tab1.str3 = "厅长"    --给一个表新字段赋值是可以的
print(tab1.str3)      --output ：可以

--定义“元表实现函数”
function AddValue(tab,k,v)
    --使用rawset()函数，可以撤销元方法的作用，但本实现函数还是要执行的
    --rawset(tab,k,v)
    print("我们检测到你给元表添加了新的数据 k="..k.."v="..v)
end
setmetatable(tab1,{__newindex=AddValue})
tab1.str4 = "局长"
tab1.str1 = "行长"
print(tab1.str4)
print(tab1.str1)