---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by siyin.liu.
--- DateTime: 2021/4/18 20:19
---
myTable = setmetatable({key1 = "value"},
        {__newindex = function(myTable,k,v)
            rawset(myTable,k,"----"..v.."----")
            print("__newindex 核心处理函数被执行了")
        end})
myTable.key1 = "new value"
myTable.key2 = 88
print(myTable.key1, myTable.key2)