---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by siyin.liu.
--- DateTime: 2021/4/18 20:35
---
tab1 = {}
function InvokeMethod()
    print("本元表被调用")
end
setmetatable(tab1,{__call = InvokeMethod})
print(tab1)
print(tab1())--相当于一个Table被执行。即就是元方法核心处理函数，成为了表中的一个函数。

tab2 = {10,20,30}
function InvokeMethod2(num1,num2,num3,num4)
    print("本表被调用2")
    return num1,num2,num3,num4
end
setmetatable(tab2,{__call = InvokeMethod2})
print("调用的结果=",tab2(tab2[1],tab2[2],tab2[3]))
