---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2021/5/8 10:09
---
--使用”loadfile“函数,调用lua外部脚本
--local externalFile = loadfile("Test/C015_IsInvokedLua.lua")   --可以 相对路径
local externalFile = loadfile("D:/Projects/Lua/LuaLearn/LuaLearn/src/Test/C015_IsInvokedLua.lua") --绝对路径
--local externalFile = loadfile("中级篇/C015_调试与运行/C015_IsInvokedLua.lua") --中文的文件访问不到不知道为什么
--local externalFile = loadfile("D:/Projects/Lua/LuaLearn/LuaLearn/src/中级篇/C015_调试与运行/C015_IsInvokedLua.lua")--中文的文件访问不到不知道为什么
--测试得到的外部lua变量
print(externalFile)
print("变量的类型： ",type(externalFile))
--调用此函数
externalFile()      --本步骤是必须的，如果不调用后面调用外部将本的变量和函数会报错 attempt to call global 'ShowInfo' (a nil value)
--调用外部文件函数与变量
ShowInfo()          --调用全局函数
print(num1)         --调用全局变量
print(num2)         --调用局部变量  获取不到： 输出结果是nil
ShowInfoByLocal()   --调用局部函数 会引发异常 attempt to call global 'ShowInfoByLocal' (a nil value)
