---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2021/5/8 11:34
---
--[[
    使用dofile函数，调用外部脚本
    规律：dofile 函数，不返回结果也无需执行返回结果。即：直接编译且运行外部lua脚本
]]

local externalFile2 = dofile("Test/C015_IsInvokedLua.lua")
--测试得到的外部lua变量
print(externalFile2)
print("变量的类型: ",type(externalFile2))
print("==================")
ShowInfo()          --调用全局函数
print(num1)         --调用全局变量
--print(num2)         --调用局部变量
--ShowInfoByLocal()   --调用局部函数