---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2021/5/8 13:58
---
--[[
    学习使用loadstring函数，直接执行lua代码
]]
local result1 = loadstring("print('This is lua info')")
--测试
print(result1)
print("result1 type:",type(result1))

--运行返回函数
result1()
print("===演示 loadstring 函数性质1，总是在全局环境下编译字符串===")
num1 = 1000
local num1 = 30
fun1 = loadstring("num1 = num1 + 1 print(num1)")
fun2 = function()
    num1 = num1 + 1
    print(num1)
end
fun1()          --1001
fun2()          --31
print("==演示 loadstring 函数性质2：字符串形式的lua脚本，如果出错，则不会显示错误信息======")
local res1 = loadstring("Hello")
print(res1)

print("解决以上问题，assert()函数")
local  res2 = assert(res1,"error")
