---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2021/5/8 16:57
---
--[[
    error() 函数抛出异常/错误
]]
--[[
local num = nil
if( not num) then
    error("error: 出现错误了请输入合法数值")
else
    print("输入的数值合法进入下一页、")
end
]]
--[[local num = nil
result = assert(num,"Error: 请输出合法数值：")
print(result)]]

--进一步距离,关于Asset函数使用
--[[numInput = "abc"
res1 = tonumber(numInput)
print("res1=",res1)]]
numInput = "abc"
--numInput = "10"
res = assert(tonumber(numInput),"发生错误：输入一个数值型数据，不要写字符组合！")
print(res)

