---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2021/5/8 17:31
---
--[[
捕获错误/异常 pcall() / xpcall()
]]
--使用pcall()函数，来捕获错误。
--定义错误函数
function HaveError()
    error({error = "本方法有错误发生"})
end
local resFlag, errorInfo = pcall(HaveError)
if(resFlag) then
    print("正确执行代码")
else
    print("发生错误：",errorInfo.error)
end

print("=====使用xpcall来捕获错误======")
function HaveError2()
    error({error = "本方法有错误发生"})
end
--错误的处理函数(如何处理错误)
function ProcessError()
    print("发生错误:，详细堆栈信息如下： ")
    print(debug.traceback())
end
local resFlag = xpcall(HaveError2,ProcessError)
if(resFlag)then
    print("正确执行语句")
end
print("后续语句，继续运行。。。。")