---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2021/5/8 18:06
---
--[[
Lua语言使用collectgarbage()函数来做垃圾回收机制
]]
print("step1 显示lua占用的总内存数 ",collectgarbage("count")) --显示lua占用的总内存数[以k字节为单位]。字符串是固定好的
print("开始给table填充大量数据")
myTable = {}
for i = 1, 100000 do
    myTable[i] = i
end
print("step2 显示lua占用的总内存数 ",collectgarbage("count")) --显示lua占用的总内存数。字符串是固定好的
--Table   资源释放
myTable = nil
print("step3 显示lua占用的总内存数 ",collectgarbage("count"))  --显示lua占用的总内存数
--强制进行垃圾收集处理
collectgarbage("collect",myTable)
print("step4 显示lua占用的总内存数 ",collectgarbage("count"))  --显示lua占用的总内存数
