---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2021/1/18 18:28
---
--[[
字符串定义
    是由数字、字母、下划线组成的一串字符。
    lua语言中字符串可以使用以下三种方式来表示：
        单引号间的一串字符。
        双引号间的一串字符
        [ [ 和 ] ]间的一串字符
]]
