---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2021/1/19 10:24
---
--[[
转义字符串
    常用的转义字符串
        回车  \r
        换行  \n
        反斜杠 \\
        双引号 ""
]]

print("Hello\nWorld")      --换行
print("你们好吗？\r我们还好")  --回车
print("大家\好")
print("大家\\好") --输出反斜杠，一般常用来表示磁盘的路径
print("D\\Programe\\lua\\IED")
print("ni\"hai\"hao")
print('ni"hai"hao')
print("ni'hai'hao")
print("Hello\r\nWorld")