---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2021/2/18 9:24
---
--[[
OOP编程概念：
    面向对象编程(Object Oriented Programming,OOP)是一种目前非常主流的计算机编程思想。
    目前支持OOP编程的有：Smalltalk、Java、C#、Objective-Created、C++等。
    OOP编程三大核心：
        封装：指能够把一个实体的信息、功能、响应都能装入一个单独的对象中的特性。
        继承：继承的方法允许在不改动原程序的基础上对其进行扩充，这样使得原功能也得以保存，而新功能也得以扩展。这有利于减少重复编码，提高软件的开发效率。
        多态：同一操作作用于不同的对象，可以有不同的解释，产生不同的执行结果。
    lua的语法没有面向对象的机制。
    lua中使用Table实现面向对象机制。把Table模拟一个“类”来使用。
    提示：其实lua的string(math、random)等就是可以看成面向对象的特殊表。
]]--