---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2021/2/18 10:11
---
--[[
    演示函数中如何提高灵活性问题。
    改进函数的定义方式。
]]--
--定义空表，相当于是一个(OOP编程中的)"类"
Person = {}
--引入this变量
local thisa = Person
--thisa = Person //也可以达到效果
--定义"字段"
Person.Name = "小明"
Person.Gender = "男"
Person.Weight = 175
Person.Height = 150
--定义方法
Person.Speak = function() --第一中定义方式“匿名函数”
    print("人在说话")
end
function Person.Walking() --第二种定义方式(常用)
    print("人在走路")
end
-- 输出个人信息(函数中调用函数)
function Person.ShowInfo()
    print("调用我的个人信息")
    print("身高："..thisa.Height)
    print("体重："..thisa.Weight)
    thisa.Speak()
    thisa.Walking()
end
--调用“字段”与“方法”
print(Person.Name)
print(Person.Gender)
print(Person.Weight)
print(Person.Height)
--调用“方法”
Person.Speak()
Person.Walking()
Person.ShowInfo()
--演示函数中，增加“this”变量提高灵活性问题。
a = Person
Person = nil
a.ShowInfo()