---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2021/2/18 11:29
---
--定义空表，相当于是一个(OOP编程中的)"类"
Person = {}
-- local thisa = Person -- 使用self关键字，可以代替
--定义"字段"
Person.Name = "小明"
Person.Gender = "男"
Person.Weight = 175
Person.Height = 150
--定义方法
Person.Speak = function() --第一中定义方式“匿名函数”
    print("人在说话")
end
function Person.Walking() --第二种定义方式(常用)
    print("人在走路")
end
-- 输出个人信息
-- 进一步完善函数的定义方式，使用self关键字。(配合函数使用“冒号”定义函数)
function Person:Show()
    print("调用我的个人信息")
    print("身高："..self.Height)
    print("体重："..self.Weight)
    self.Speak()
    self.Walking()
end
--演示函数中，增加“this”变量提高灵活性问题。
a = Person
Person = nil
a:Show() -- 更加完善与常用的方法调用方式