---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2021/1/19 16:14
---
--[[
表的赋值与迭代输出
    空表的赋值与迭代输出
    数组类型表的迭代输出
    字典类型表的赋值与迭代输出
    使用迭代器函数输出：
        ipairs 函数
            输出连续数值
        pairs 函数
            输出连续与非连续（键值对）数值
        "#"符号，除了可以取得字符串长度还可以取的表的长度（表是数组时可以用）
]]
print("表的'数组类型'的迭代输出")
tableArray1 = {}
tableArray1[1] = 13
tableArray1[2] = 33
tableArray1[3] = 14
tableArray1[4] = 45
for i = 1 ,4,1 do
    print(string.format("表的数组类型输出 方式1 tableArray1[%d]: %d",i,tableArray1[i]))
end
print("使用table 函数或者符号输出")
for i = 1, #tableArray1 do --使用"#"符号得到表中数量,只使用与Table是“数组类型”
    print(string.format("表的数组类型输出 方式2 使用#符号 tableArray1[%d]: %d",i,tableArray1[i]))
end
for k,v in ipairs(tableArray1) do
    print(string.format("表的数组类型输出 方式3 使用iparis tableArray1[%d]:%d",k,v))
end
for k,v in pairs(tableArray1) do
    print(string.format("表的数组类型输出 方式4 使用pairs tableArray1[%d]:%d",k,v))
end
print("表的'字典类型'的迭代输出")
tableDictionary1 = {str1 = "张三", str2 = "李四", str3 = "王五"} --定义表，且直接赋值。
tableDictionary1.str4 = "孔明"
tableDictionary1["str5"] = "孙悟空"
for i = 1, 5,1 do
     print(string.format("表字典类型的输出 方式1:tableDictionary1[str%s]: %s","str"..i, tableDictionary1["str"..i]))
end

for k,v in pairs(tableDictionary1) do
    print(string.format("表字典类型的输出 方式2 使用pairs tableDictionary1[\"%s\"]:%s",k,v))
end

tableArray2 = {"zhang","he","li"}
for m,n in ipairs(tableArray2) do
    print(m,n)
end